spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql:true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    org.hibernate.sql: debug


